services:
  app:
    image: app
    build: 
      context: .
      dockerfile: Dockerfile
      target: developer
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: go run cmd/main.go